# Địa chỉ kho SQL Server (Cổng mặc định là 1433)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=auth_db;encrypt=true;trustServerCertificate=true;

# Tài khoản và Mật khẩu SQL Server
spring.datasource.username=sa
spring.datasource.password=123456

# Báo cho Spring biết đang dùng SQL Server
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect

# Tự động tạo bảng
spring.jpa.hibernate.ddl-auto=update